### ISSUE TITLE
[data-invalid] attributes should be set to a boolean value

### ISSUE THREAD

**Issue by chaseoli** [carbon-design-system/carbon-contribution#2]
My team is using vanilla carbon with our project. Our project is written in angular using the vanilla repos since the carbon-angular repo is not supported. This works fine for most of our usage except the scss related to the data-invalid attribute is problematic for us since angular doesn't allow for logic to fully remove and add the data-invalid attribute directly from and HTML element. Ideally we would like to be able to use the following:

```html
<div class="bx--form-item">
	<input id="name" [attr.data-invalid]="angular_boolean_value_here"[(ngModel)]="data.participant.name" type="text" class="bx--text-input">
	<label for="name" class="bx--label">Institution Name</label>
	<div class="bx--form-requirement">
		Required
	</div>
</div>
```

Unfortunately, this doesn't work since the scss does not evaluate the true/false value:
```scss
// current scss:
 &[data-invalid],
 &[data-invalid]:focus {
      box-shadow: 0 2px 0 0 $support-01;
}
```

I propose changing all instances of this to something like:
```scss
// current scss:
 &[data-invalid="true"],
 &[data-invalid="true"]:focus {
      box-shadow: 0 2px 0 0 $support-01;
}
```
This way the vanilla styles work easily with angular. 

If you agree, I can do a PR and make the requested changes.
